# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='teste_novidade',
            field=models.TextField(default='Default', max_length=5000),
        ),
    ]
