# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_message_teste_novidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='teste_novidade',
        ),
    ]
