# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0004_message_teste_novidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='teste_novidade2',
            field=models.TextField(default='Default', max_length=5000),
        ),
    ]
