# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lares.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Anúncio Ativo')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=120)),
                ('bairro', models.CharField(max_length=120)),
                ('rua', models.CharField(max_length=120, verbose_name='Rua, avenida, alameda')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('referencia', models.CharField(blank=True, max_length=120, null=True, verbose_name='Referência')),
                ('tipo_imovel', models.CharField(default='Casa', max_length=20, verbose_name='Tipo de Imóvel')),
                ('area_util', models.PositiveIntegerField(blank=True, null=True, verbose_name='Área Útil (m²)')),
                ('qtd_quartos', models.PositiveIntegerField(verbose_name='Quantidade de Quartos')),
                ('qtd_banheiros', models.PositiveIntegerField(verbose_name='Quantidade de Banheiros')),
                ('qtd_vagas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas de Garagem')),
                ('mobiliado', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True, help_text='Mobiliado, piscina, quintal, área externa, etc.', null=True, verbose_name='Descrição do Imóvel')),
                ('preco_locacao', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Aluguel')),
                ('preco_condominio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Condomínio (se houver)')),
                ('iptu', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='IPTU')),
                ('conta_agua', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Conta de água')),
                ('conta_luz', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Conta de luz')),
                ('move_in_date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updates', models.DateTimeField(auto_now=True)),
                ('visita_fotografica', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-timestamp', '-updates'],
            },
        ),
        migrations.CreateModel(
            name='ImovelPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('photos', models.ImageField(height_field='height', upload_to=lares.models.upload_location, verbose_name='Fotos', width_field='width')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lares.Imovel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
