# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lares', '0002_imovel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='visita_fotografica',
        ),
    ]
