# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lares', '0004_auto_20170619_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovelphotos',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='imovelphotos',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
