# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lares', '0006_auto_20170619_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovelphotos',
            options={'ordering': ('order_order',)},
        ),
        migrations.AddField(
            model_name='imovelphotos',
            name='order_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
