# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lares', '0007_auto_20170619_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovelphotos',
            options={'ordering': ('order',)},
        ),
        migrations.RenameField(
            model_name='imovelphotos',
            old_name='order_order',
            new_name='order',
        ),
    ]
