# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lares', '0008_auto_20170619_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelphotos',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
