# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_complemto', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('caracteristicas', models.TextField(help_text='procuro um apê de 2 quartos próximo da UFSCar. Tenho um carro e um cachorro.', max_length=5000, verbose_name='número de quartos, local, faixa de preço, etc...')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
