# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='caracteristicas',
            field=models.TextField(max_length=5000, verbose_name='número de quartos, local, faixa de preço, etc...'),
        ),
    ]
