# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170607_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='nome_complemto',
            new_name='nome_completo',
        ),
    ]
